// Generated by CoffeeScript 1.6.2
(function() {
  exports.postStart = function(context) {
    var repl;

    repl = context.repl;
    return repl.inputStream.on("keypress", function(char, key) {
      if (!(key && key.ctrl && !key.meta && !key.shift && key.name === "l")) {
        return;
      }
      repl.outputStream.write("\u001B[2J\u001B[0;0f");
      return repl.displayPrompt();
    });
  };

}).call(this);
